---
#

- name: copy user_sfc_scenarios_variables.yml (SUSE)
  template:
    src: "{{xci_flavor}}/user_sfc_scenarios_variables_suse.yml.j2"
    dest: "{{openstack_osa_etc_path}}/user_sfc_scenarios_variables.yml"
  when: ansible_pkg_mgr == 'zypper'

- name: copy user_sfc_scenarios_variables.yml (Ubuntu)
  template:
    src: "{{xci_flavor}}/user_sfc_scenarios_variables_ubuntu.yml.j2"
    dest: "{{openstack_osa_etc_path}}/user_sfc_scenarios_variables.yml"
  when: ansible_pkg_mgr == 'apt'

# To get the mano_host variable (can only be defined here for the inventory)
- name: copy openstack_user_config.yml
  copy:
    src: "tacker_files/{{xci_flavor}}/openstack_user_config.yml"
    dest: "{{openstack_osa_etc_path}}/openstack_user_config.yml"
