---
#

- name: copy user_sfc_scenarios_variables.yml
  copy:
    src: "{{XCI_FLAVOR}}/user_sfc_scenarios_variables.yml"
    dest: "{{OPENSTACK_OSA_ETC_PATH}}/user_sfc_scenarios_variables.yml"

- name: copy OPNFV role requirements
  copy:
    src: "ansible-role-requirements-master.yml"
    dest: "{{OPENSTACK_OSA_PATH}}/ansible-role-requirements.yml"

- name: copy openstack_services.yml with tacker
  copy:
    src: "tacker_files/openstack_services-master.yml"
    dest: "{{OPENSTACK_OSA_PATH}}/playbooks/defaults/repo_packages/openstack_services.yml"
