---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 SUSE Linux GmbH
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Add SFC repos and inventory for Pike
  include: add-sfc-repos-and-inventory-pike.yml
  when: OPENSTACK_OSA_VERSION == "stable/pike"

- name: Add SFC repos and inventory for master
  include: add-sfc-repos-and-inventory-master.yml
  when: OPENSTACK_OSA_VERSION != "stable/pike"

- name: Copy the OSA not-yet-upstreamed files for Pike
  include: copy-OSA-files-pike.yml
  when: OPENSTACK_OSA_VERSION == "stable/pike"

- name: Copy the OSA not-yet-upstreamed files for master
  include: copy-OSA-files-master.yml
  when: OPENSTACK_OSA_VERSION != "stable/pike"
