# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: clone OSM devops repo and checkout version {{ osm_devops_version }}
  become_user: "{{ osm_install_user }}"
  become: yes
  git:
    repo: "{{ osm_devops_git_url }}"
    dest: "{{ osm_devops_clone_location }}"
    version: "{{ osm_devops_version }}"

- name: install OSM
  become_user: "{{ osm_install_user }}"
  become: yes
  command: "/bin/bash ./install_osm.sh -y --nolxd"
  args:
    chdir: "{{ osm_devops_clone_location }}/installers"
    creates: "/usr/bin/osm"
