---
#

- name: copy user_sfc_scenarios_variables.yml (Ubuntu)
  template:
    src: "{{xci_flavor}}/user_sfc_scenarios_variables_ubuntu.yml.j2"
    dest: "{{openstack_osa_etc_path}}/user_sfc_scenarios_variables.yml"
  when: ansible_pkg_mgr == 'apt'
