---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 Venkata Harshavardhan Reddy Allu and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: copy user_sfc_scenarios_variables.yml (Ubuntu)
  template:
    src: "{{xci_flavor}}/user_sfc_scenarios_variables_ubuntu.yml.j2"
    dest: "{{openstack_osa_etc_path}}/user_sfc_scenarios_variables.yml"
  when: ansible_pkg_mgr == 'apt'

- name: copy openstack_user_config.yml
  copy:
    src: "{{xci_flavor}}/openstack_user_config.yml"
    dest: "{{openstack_osa_etc_path}}/openstack_user_config.yml"
