---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 Venkata Harshavardhan Reddy Allu and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: wait until all containers in OSM stack are ready
  shell: "docker stack services osm | awk 'NR>1 {print $4}' |  grep -c '0/1'"
  register: result
  until: result.stdout == '0'
  failed_when: result.rc == '0'
  delay: 120
  retries: 10

- name: Register OpenStack as VIM
  command: >
    osm vim-create
    --name openstack-site
    --user admin
    --password "{{ openrc_os_password }}"
    --tenant admin
    --account_type openstack
    --auth_url "{{ openrc_os_auth_url }}"
    --config='{insecure: true}'
  changed_when: False
